In [29]:
import numpy as np
import pandas as pd
df=pd.read_csv('Train.csv')
df1=pd.read_csv('Test.csv')
df.head()

   feature_1  feature_2  feature_3  feature_4  feature_5     target
0   0.293416  -0.945599  -0.421105   0.406816   0.525662 -82.154667
1  -0.836084  -0.189228  -0.776403  -1.053831   0.597997 -48.897960
2   0.236425   0.132836  -0.147723   0.699854  -0.187364  77.270371
3   0.175312   0.143194  -0.581111  -0.122107  -1.292168  -2.988581
4  -1.693011   0.542712  -2.798729  -0.686723   1.244077 -37.596722

In [30]:
df1.head()

   feature_1  feature_2  feature_3  feature_4  feature_5
0   1.015254   2.076209  -0.266435  -2.418088  -0.980503
1  -0.375021   0.953185   0.626719   0.704406  -0.355489
2  -1.024452   0.962991  -0.407942  -1.861274   0.455201
3  -2.489841   0.544802   0.601219  -0.607021  -1.314286
4  -0.384675  -0.833624   1.358552  -0.547932   0.411925

In [31]:
df.isnull().sum()

feature_1    0
feature_2    0
feature_3    0
feature_4    0
feature_5    0
target       0
dtype: int64

In [32]:
x=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [33]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split   
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)
linReg=RandomForestRegressor()
linReg.fit(x_train,y_train)

y_pred=linReg.predict(x_test)
from sklearn.metrics import explained_variance_score       
a=explained_variance_score(y_test,y_pred)
a

0.9364147017734696

In [37]:
y_pred1=linReg.predict(df1)
y_pred1

array([ 151.43291799,  108.98513606,   -9.13635408,  -22.49956165,
       -107.06240833,  -50.17136945,  -67.27554273,   40.41369161,
        158.50222158,  173.10955869, -112.3806589 ,  -15.28060968,
        -19.35853122,  121.4263516 ,   30.24261709,   43.9317342 ,
       -228.84002561,   30.38659332,   37.36565908,  131.74124307,
         68.07183667,  -70.86672951,  -97.18809276,  -22.46674711,
        -49.10638754,   22.56538437,   15.62627364,  129.70117486,
          3.35007249,  -27.38398312,  108.21319849,  -34.93591499,
        213.00479338,  -30.11516811, -215.93559039,  157.09836196,
        -26.78836821,   32.321401  , -238.25739173,   72.25832544,
        -86.89734272, -197.82017414, -244.56176505,  119.02093589,
       -120.17332748,   98.77284342,   -9.93556144,    8.0967845 ,
       -100.94406089,  -43.78319355,   32.38554644, -195.89171243,
         63.61352773,  -95.51985013, -112.77541273, -135.67681457,
         64.44004682,  141.49875957,  -61.37399326,   48.47939133,
         41.46030461,  -66.18913812,  163.28994539,   32.81923872,
         56.1487993 ,   14.48721809,   80.21446006,   -2.74347738,
         -0.74008442,   -3.82442412,  -13.15255331,  148.69181928,
        -37.63954411,   38.02853038,  -76.69241444, -101.63985928,
         34.87348321, -148.55925671,   17.08519797,  153.32613828,
        -40.54657679, -136.12448384, -153.52637454,   45.41119713,
        156.34232083,  276.2979821 , -264.05285822, -134.88807473,
        108.00069451,  -88.632162  ,  -42.39071529,   91.56182503,
       -166.13466825, -114.40294372,   46.5368258 ,   93.79036788,
       -237.65591601, -107.89079963, -177.32138434,  -52.7069311 ,
        143.71258676,  -69.12688442,   -4.04306481,    3.06729999,
        -17.17271668,   41.57702284,   28.39709751,  104.86700879,
        -21.51586548,  -83.23744499,   51.28673704,   26.5575278 ,
        114.78851672,    2.78000572,   64.98126952,   35.60698698,
       -142.39299339,   -7.62541061,   33.62062844,  -18.77809578,
        -14.93201403, -255.80017306,  225.09232313,  168.58185047,
         16.85114275,   95.66686706,  -17.51275979, -133.35253671,
        101.74515211,  -36.9636469 , -234.06764064,  119.74003971,
        -23.52260457,  -87.82448124,  179.85422741,   32.77622759,
          6.15318646,   33.80278142,   20.37204377, -164.27861262,
        137.99634465,  -79.88447681,  182.84059066,  118.71708756,
        -48.59221979, -138.03512692,  -35.86450028,  149.70406815,
         32.50120055,   59.22241908,    3.89943341,  -55.61365661,
         -1.33496079,  -67.01765647,    9.6926936 ,  139.48895767,
        297.57902482,  205.03693509,   32.15409414,  -31.7799842 ,
       -157.9330537 ,   -2.79924931,  263.86639239,   95.43937336,
        -25.41564308,  158.80393134, -157.50504065,  116.39974732,
        164.18577531,  -48.05165629,   66.34064895,   47.45303652,
         75.40200512,   21.30088725,  180.0715656 , -152.19285828,
        -99.38823965, -143.29350707,  -12.11538961,  -97.245846  ,
        -18.19800019,  -45.94373356,  -68.73457784,   50.94954396,
        -78.5098883 ,   86.48729115,  -55.4239622 ,  -97.87109037,
        -65.50008942,  187.57480186,  -33.00649223,  216.04089409,
        -62.14317338,  -84.66515503,   57.48046032,   -3.40286198,
         82.67284443,  -52.64813388,  203.55457433, -147.60619244,
        -98.4604248 ,  -74.05638129,   28.76378024,   49.45838198,
        147.493241  ,   27.90998723,  100.60385184,  130.02021102,
       -260.875608  , -176.37252693, -114.42493993,  -67.42855195,
         28.17908238,  -57.99982909,   77.58719432,   -8.99824074,
        -47.20872837,  -27.70029663,   49.0695024 ,   81.43578846,
       -109.44695733, -129.3924261 ,   28.49639733,  208.20611258,
        -38.33348419,   16.29776432,  -24.95384887,    0.89647498,
          6.59461683,   37.2135483 ,  136.41795564,   26.19205515,
        -89.61028114,   64.67968801,   81.15213969, -141.33536294,
       -150.00327025,  158.73371624,  113.46574848,   22.07183546,
        -10.09940377,  -16.49660922,  -47.80587424, -161.41694855,
        -45.18053489,  -26.37837136, -152.32576938,  -19.35527743,
         16.24207708, -106.04650818,   34.90289016,   -2.74980687,
       -272.69704467, -210.04083624, -152.0065058 ,   54.87227108,
        115.02894083,   46.64185037,  123.9461634 ,   80.88568036,
          8.53788429, -311.10004029,  201.58051872, -125.15778816,
        -36.52749219, -126.06488575,  -84.39842787,  129.63422733,
        172.71685649,  -33.94152753, -133.02128149,   92.64783213,
        -16.1599826 ,   93.84950003,  102.85863174,   23.77944207,
        -44.19647251,  -52.4261726 ,   35.65609561,   99.09846065,
         30.09849944, -137.50995063,  -14.58787323,  -27.1336079 ,
       -131.09820431,  158.778644  ,   -9.55909753, -123.8466476 ,
        194.95414869,   44.62567118,   76.75559983,   41.36010766,
        201.67279834,  -36.71518593,  -27.93204658,  -63.14202938,
         61.05734071,  -78.45323369,  104.4645247 ,  -74.37029621,
       -102.19926048,  -21.27109661,  -92.51737757,  -28.19447616,
         54.30662164,  -47.29408206,  -70.45628883, -162.9541497 ,
       -182.10033523,   58.60722133,   19.62245505,  269.8296327 ,
        134.02545768,  140.64342489,   29.93759539,  -36.54638927,
        183.54629267,  -41.25083139,   89.87160051,  161.43479539,
        -38.85476267, -176.75650676,  -98.43116603,    2.79879917,
        -35.08979764,  -30.10615891,  171.85797857,  121.09406617,
         34.48267543,  -88.91200518,  174.71862164,  -56.22524051,
         60.19692147,   61.5317829 ,   96.10358627,  -89.55417255,
        102.69139257,  -39.33902492,   84.49096285,  -40.65673993,
       -158.47109051,  149.61042811,  -95.92888774,   12.43741452,
        146.70379914,   36.01120849, -164.33063877,  -21.40629178,
        -35.81059587, -107.51765107,    1.01069113,  -99.35703515,
        -59.21034619, -191.06438352, -199.57539612,   -8.38132949,
       -192.49998643,  182.8035151 ,  -18.97420837,   32.19004493,
         36.9061339 ,  214.79739885,  -36.20405049,  101.27615695,
         46.512157  ,   24.10106451,  -76.05114996,  -16.13926993,
        227.02006214,  -31.36552786, -131.55559539,  -31.05844911,
        -84.313348  ,   -8.09963577,  -22.0498792 ,  -56.34162592,
        -23.26879671, -180.48691391, -123.80815558,   45.26289232,
        -38.89373906, -141.72921787,  107.87102523,  -13.08804838,
        129.31799052,  -16.48527012,   -9.01775548,  179.50408058,
        171.37555976,   44.06094543,  -32.08159861,   58.8760008 ,
         99.46673887,  -40.75972322,  -50.44245067,  -80.75252199,
       -193.09304811,  137.63402439,   74.95027812,   68.69059582])